/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'Nu-LB-NUC140_7seg' 
 * Target:  'GPIO' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "NUC100Series.h"



#endif /* RTE_COMPONENTS_H */
